### ISSUE TITLE
Configure Nginx as proxy for JupyterHub

### ISSUE THREAD

**Issue by elventear** [radiasoft/ansible-conf#13]

**Comment by elventear** [comment]
I have managed to use docker-nginx as a proxy, but can't make the SSL certificates work for some reason.

**Comment by robnagler** [comment]
What's the error?

**Comment by elventear** [comment]
The connection just gets dropped.

```sh
curl 'https://alpha-jupyter.radiasoft.org'
curl: (35) Unknown SSL protocol error in connection to alpha-jupyter.radiasoft.org:443
```

But I don't see any errors on the nginx logs.

**Comment by elventear** [comment]
Managed to make it work with manually configured nginx running within the host. So far I haven't been able to make the container work with SSL.

**Comment by elventear** [comment]
Mounted the entire configuration from the working proxy (`/etc/nginx`) into the container, still doesn't work. I wonder if it's missing SSL support?
