### ISSUE TITLE
Centralize all the secrets into one file

### ISSUE THREAD

**Issue by elventear** [radiasoft/ansible-conf#23]

**Comment by robnagler** [comment]
I'm not sure this is the right approach. We want to share some secrets across hosts and others on a single host. Let's discuss when the task comes up for development.

**Comment by elventear** [comment]
The idea is that this secrets file is a collection of values with a label attached. When can use the reference label as we see fit when organizing different hosts. 

Since the secrets are going to be maintained manually it would be better if they can be in one place.

**Comment by robnagler** [comment]
I guess it makes sense still. Never mind. :)

**Comment by elventear** [comment]
Centralized via `rs_vars`.
