### ISSUE TITLE
Configure Jupyter Server security

### ISSUE THREAD

**Issue by elventear** [radiasoft/ansible-conf#58]
Jupyter can use a token or password to ensure access by the right users. In order to use nginx as a proxy, I need to know the token in advance, disable it all together and rely on the authentication of nginx or use a password within Jupyter. 

A location for these settings might be in `/home/vagrant/.jupyter/jupyter_notebook_config.json` 

Required by #57.

**Comment by robnagler** [comment]
Let's use the jupyter password if it is easier than setting up nginx auth.

**Comment by elventear** [comment]
Another way of getting the token:

```sh
jupyter notebook list | grep token  | egrep -o '=([0-9a-z]+)' | tr -d '='
```

**Comment by elventear** [comment]
Simples solution is to specify a token before hand, use that token on an nginx header and user nginx auth.
